### ISSUE TITLE
paging=0;10 not workong - return 401 Unauthorized

### ISSUE THREAD

**Issue by qwertmax** [upwork/golang-upwork#1]
params := make(map[string]string)
	params["q"] = "golang"
	params["paging"] = "0;10"
	client.SetEntryPoint("api/")

	req, body := client.Get("profiles/v2/search/jobs.json", params)

looks like it not like ";" in signing

**Comment by mnovozhylov** [comment]
Hello Max,

thanks for the feedback. We will investigate the behavior ASAP, but before please fix your code - you shouldn't use "client.SetEntryPoint("api/")" unless you understand for 100% what you're doing, moreover - in your sample it was used incorrectly.

**Comment by mnovozhylov** [comment]
@qwertmax , please do `go get -u github.com/mnovozhylov/oauth`

**Comment by qwertmax** [comment]
awesome! Thank you!
