### ISSUE TITLE
Archive or Support?

### ISSUE THREAD

**Issue by brendancol** [upwork/golang-upwork#15]
First, thank you for your efforts in developing and maintaining Golang bindings for Upwork.

I wanted to bring to your attention that Upwork has transitioned to using OAuth2 for authentication and has introduced a new GraphQL API. The current implementation of this repository still relies on the deprecated authentication methods and the old REST API.

Given these changes, are there any plans to update the library to support OAuth2 and the new GraphQL interface? Updating the bindings would ensure compatibility with Upwork's current API offerings and allow developers to utilize the latest features and improvements.

If updating is on the roadmap, could you provide an estimated timeline? If not, would you consider archiving any language binding that are no longer supported?

**Comment by mnovozhylov** [comment]
Hello,
Thank you for the note. Please, check https://github.com/upwork/golang-upwork-oauth2
